// Field registries for Asana resource types, used by describe command
export const TASK_FIELDS = [
  "gid",
  "name",
  "completed",
  "completed_at",
  "assignee",
  "assignee.name",
  "assignee.email",
  "due_on",
  "due_at",
  "start_on",
  "start_at",
  "notes",
  "html_notes",
  "tags",
  "tags.name",
  "projects",
  "projects.name",
  "memberships.section.name",
  "parent",
  "parent.name",
  "num_subtasks",
  "permalink_url",
  "created_at",
  "modified_at",
  "custom_fields",
  "custom_fields.name",
  "custom_fields.display_value",
  "followers",
  "followers.name",
] as const;

export const PROJECT_FIELDS = [
  "gid",
  "name",
  "archived",
  "color",
  "icon",
  "privacy_setting",
  "completed",
  "completed_at",
  "completed_by",
  "completed_by.name",
  "owner",
  "owner.name",
  "team",
  "team.name",
  "workspace",
  "workspace.name",
  "notes",
  "html_notes",
  "permalink_url",
  "created_at",
  "modified_at",
  "due_on",
  "start_on",
  "default_view",
  "default_access_level",
  "minimum_access_level_for_customization",
  "minimum_access_level_for_sharing",
  "current_status_update",
  "current_status_update.title",
  "followers",
  "followers.name",
  "members",
  "members.name",
  "custom_fields",
  "custom_fields.name",
  "custom_fields.display_value",
] as const;

export const WORKSPACE_FIELDS = [
  "gid",
  "name",
  "is_organization",
  "email_domains",
] as const;

export const SECTION_FIELDS = [
  "gid",
  "name",
  "created_at",
  "project",
  "project.name",
] as const;

export const USER_FIELDS = [
  "gid",
  "name",
  "email",
  "photo",
  "workspaces",
  "workspaces.name",
] as const;
